import { GoogleGenerativeAI } from '@google/generative-ai';

let genAI: GoogleGenerativeAI | null = null;

export function getGemini(): GoogleGenerativeAI | null {
  if (genAI) return genAI;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('[gemini] Missing GEMINI_API_KEY — running in mock mode');
    return null;
  }

  genAI = new GoogleGenerativeAI(apiKey);
  return genAI;
}

/**
 * Embed a text string using Gemini gemini-embedding-001 model.
 * Uses v1beta REST API with outputDimensionality=768 to match Pinecone index.
 * Returns a 768-dimensional float array.
 */
export async function embedText(text: string): Promise<number[]> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    // Return a dummy 768-dim vector in mock mode
    return new Array(768).fill(0);
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'models/gemini-embedding-001',
        content: { parts: [{ text }] },
        outputDimensionality: 768,
      }),
    },
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Embedding API error (${response.status}): ${err}`);
  }

  const data = await response.json();
  return data.embedding.values;
}

/**
 * Generate an ELI5 response using Gemini 2.5 Flash (free tier).
 * Includes retry logic for rate-limit (429) errors.
 */
export async function generateELI5(
  userQuery: string,
  context: string,
  language: string,
  role: string,
): Promise<string> {
  const ai = getGemini();
  if (!ai) {
    return `[Mock Response] Here is a simplified explanation for "${userQuery}" based on the available schemes. In production, this will be generated by Gemini.`;
  }

  const model = ai.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `You are GovGuide, a friendly government schemes assistant for Indian citizens.

ROLE: The user is a ${role}.
LANGUAGE: Respond in ${language === 'en' ? 'English' : language === 'hi' ? 'Hindi' : language === 'ta' ? 'Tamil' : 'English'}.

INSTRUCTIONS:
- Explain Like I'm 5 (ELI5). Use the simplest possible language.
- ONLY use the context provided below. Do NOT invent schemes.
- Structure your response as:
  1. What the benefit is (1-2 sentences)
  2. Who is eligible (1 sentence)
  3. The exact first step to take (1 sentence)
- If the context does not contain relevant information, say: "I couldn't find a matching scheme. Try asking about specific topics like crop insurance, scholarships, or business loans."
- Keep the response under 150 words.
- Always end with: "Please verify details on official government portals."

CONTEXT (Retrieved Government Scheme Data):
${context || 'No matching schemes found in the database.'}

USER QUESTION: ${userQuery}

YOUR ELI5 RESPONSE:`;

  // Retry up to 2 times on rate-limit errors
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const result = await model.generateContent(prompt);
      const response = result.response;
      return response.text();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      if (message.includes('429') && attempt < 2) {
        const waitMs = (attempt + 1) * 5000; // 5s, 10s
        console.warn(`[gemini] Rate limited, retrying in ${waitMs / 1000}s (attempt ${attempt + 1}/3)...`);
        await new Promise((r) => setTimeout(r, waitMs));
        continue;
      }
      throw err;
    }
  }

  // Should never reach here
  return `Sorry, I'm temporarily unable to process this request. Please try again in a moment.`;
}
